apiVersion: v1
kind: Service
metadata:
  name: service
  # namespace: ingress-nginx
spec:
  type: LoadBalancer
  selector:
    app: first-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31000
